[package]
name = "lock-step-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
rand = "0.8.5"
sha2 = "0.10.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
